{{- if .Values.database.external.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetix.databaseSecretName" . }}
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: postgresql://{{ .Values.database.external.username }}:{{ .Values.database.external.password }}@{{ .Values.database.external.host }}:{{ .Values.database.external.port }}/{{ .Values.database.external.database }}
  secret-key: {{ randAlphaNum 32 | quote }}
{{- else }}
{{- fail "External database is required. Set database.external.enabled=true and provide connection details." }}
{{- end }}
